### ISSUE TITLE
Number Guessing Game

### ISSUE THREAD

**Issue by Ayan-09** [kaal-coder/HacktoberFest#12]
Number Guessing Game made using python3. Please assign me the issue under the tag hacktoberfest.

**Comment by kaal-coder** [comment]
@Ayan-09 Thanks for contributing
But it seems like my repository has been excluded from hacktoberfest.
The reason seems unknown.
So you can just do one thing, hop on to my other repository and do the same procedure.
I'll accept ASAP I get the request.

https://github.com/kaal-coder/hacktoberfest
