### ISSUE TITLE
Update the README.md with hacktoberfest banner and brief introduction

### ISSUE THREAD

**Issue by pantbibek21** [kaal-coder/hacktoberfest#19]
Hello @kaal-coder , I would like to add a hacktoberfest banner along with a brief introduction to Hacktoberfest to better provide the context of hacktoberfest and also create a better user experience to contribute. I could also add a few emojis to engage the visitors of this repo.
I would love to update README.md as my hacktoberfest contribution  if you like the idea : )
Thanks

**Comment by kaal-coder** [comment]
@priyanshu1208 yeah, you can

**Comment by pantbibek21** [comment]
@kaal-coder , I guess you meant me (@pantbibek21), right?
