### ISSUE TITLE
Excluded from hacktoberfest

### ISSUE THREAD

**Issue by The-APK** [kaal-coder/HacktoberFest#58]
Your approach to promoting open source contributions is commendable, but it's equally important to uphold transparency and integrity. Given that your repository is excluded from Hacktoberfest, falsely promoting it as part of the event is misleading and could damage the trust within the open source community. It's vital to represent your project's status accurately and earn recognition based on its actual merits. Let's work together to ensure that the open source ecosystem remains a reliable and trustworthy place for contributors. Best regards"

**Comment by Ankitv003** [comment]
how to know that a particular repository is excluded from Hacktoberfest.

> Your approach to promoting open source contributions is commendable, but it's equally important to uphold transparency and integrity. Given that your repository is excluded from Hacktoberfest, falsely promoting it as part of the event is misleading and could damage the trust within the open source community. It's vital to represent your project's status accurately and earn recognition based on its actual merits. Let's work together to ensure that the open source ecosystem remains a reliable and trustworthy place for contributors. Best regards"

**Comment by The-APK** [comment]
Once you submit a pr, check your hacktoberfest profile page. It will show the status of "excluded".

![image](https://github.com/kaal-coder/HacktoberFest/assets/130536278/07bdfb33-0317-434a-a0b9-4367bc420e36)
